<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <PublishProfile>DefaultContainer</PublishProfile>
    <ContainerRegistry>docker.io</ContainerRegistry>
    <ContainerRepository>dids13/consultaplus</ContainerRepository>
    <ContainerImageTags>latest;$(GITHUB_SHA)</ContainerImageTags>
    <ContainerPort>8080</ContainerPort>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConsultaPlus.Core\ConsultaPlus.Core.csproj" />
    <ProjectReference Include="..\ConsultaPlus.Infrastructure\ConsultaPlus.Infrastructure.csproj" />
  </ItemGroup>

</Project>
